require './graph.rb'

nodes = []
nodes << (node_aim = Node.new('Aim',-1))
nodes << (node_carefulaim = Node.new('Careful Aim',0))
nodes << (node_steadyaim = Node.new('Steady Aim',0))
nodes << (node_sniper = Node.new('Sniper',0))
nodes << (node_cripplingshot = Node.new('Crippling Shot',0))
nodes << (node_deadeye = Node.new('Deadeye',8))
nodes << (node_gunjuggler = Node.new('Gun-Juggler',8))
nodes << (node_showdown = Node.new('Showdown',0))
nodes << (node_overwatch = Node.new('Overwatch',0))
nodes << (node_sprayandpray = Node.new('Spray and Pray',3))
nodes << (node_itchytriggerfinger = Node.new('Itchy Trigger Finger',0))
nodes << (node_steadyhands = Node.new('Steady Hands',0))
nodes << (node_bulletstorm = Node.new('Bulletstorm',0))
nodes << (node_calledshot = Node.new('Called-shot',0))
nodes << (node_penetratingshot = Node.new('Penetrating Shot',0))
nodes << (node_strike = Node.new('Strike',-1))
nodes << (node_readystrike = Node.new('Ready Strike',0))
nodes << (node_aid = Node.new('Aid',-1))
nodes << (node_cauterize = Node.new('Cauterize',0))
nodes << (node_defribulatinground = Node.new('Defribulating Round',0))
nodes << (node_fortify = Node.new('Fortify',0))
nodes << (node_hasten = Node.new('Hasten',0))
nodes << (node_summonminionsmall = Node.new('Summon Minion (Small)',0))
nodes << (node_summonally = Node.new('Summon Ally',5))
nodes << (node_summonpatron = Node.new('Summon Patron',8))
nodes << (node_minionstrike = Node.new('Minion Strike',0))
nodes << (node_minionbounce = Node.new('Minion Bounce',0))
nodes << (node_minionchain = Node.new('Minion Chain',5))
nodes << (node_minionelement = Node.new('Minion Element',0))
nodes << (node_igneousminion = Node.new('Igneous Minion',0))
nodes << (node_chargedminion = Node.new('Charged Minion',0))
nodes << (node_alkalineminion = Node.new('Alkaline Minion',0))
nodes << (node_frostedminion = Node.new('Frosted Minion',0))
nodes << (node_slaggingminion = Node.new('Slagging Minion',0))
nodes << (node_minionprime = Node.new('Minion Prime',8))
nodes << (node_carefulminion = Node.new('Careful Minion',5))
nodes << (node_deadlyminion = Node.new('Deadly Minion',5))
nodes << (node_beastmaster = Node.new('Beastmaster',5))
nodes << (node_menagerie = Node.new('Menagerie',5))
nodes << (node_synergisticlink = Node.new('Synergistic Link',3))
nodes << (node_bulk = Node.new('Bulk',0))
nodes << (node_toughness = Node.new('Toughness',0))
nodes << (node_musclebound = Node.new('Musclebound',0))
nodes << (node_bastion = Node.new('Bastion',0))
nodes << (node_diehard = Node.new('Diehard',0))
nodes << (node_ironchurch = Node.new('Iron Church',0))
nodes << (node_flex = Node.new('Flex',0))
nodes << (node_onehandedwonder = Node.new('One handed Wonder',0))
nodes << (node_gunzerking = Node.new('Gunzerking',0))
nodes << (node_rage = Node.new('Rage',0))
nodes << (node_unignorable = Node.new('Unignorable',0))
nodes << (node_unstoppable = Node.new('Unstoppable',0))
nodes << (node_unbreakable = Node.new('Unbreakable',0))
nodes << (node_hellhathnofury = Node.new('Hell hath no Fury',8))
nodes << (node_juggernaut = Node.new('Juggernaut',8))
nodes << (node_tackle = Node.new('Tackle',0))
nodes << (node_bullrush = Node.new('Bullrush',0))
nodes << (node_hammerthrow = Node.new('Hammerthrow',0))
nodes << (node_finesse = Node.new('Finesse',0))
nodes << (node_spotter = Node.new('Spotter',0))
nodes << (node_dodge = Node.new('Dodge',0))
nodes << (node_evasive = Node.new('Evasive',0))
nodes << (node_dexterity = Node.new('Dexterity',0))
nodes << (node_shieldcharge = Node.new('Shield Charge',0))
nodes << (node_uncannyreflex = Node.new('Uncanny Reflex',0))
nodes << (node_rush = Node.new('Rush',0))
nodes << (node_sideswipe = Node.new('Sideswipe',0))
nodes << (node_murderchain = Node.new('Murder Chain',0))
nodes << (node_toofasttolive = Node.new('Too Fast to Live',0))
nodes << (node_splittingstrike = Node.new('Splitting Strike',0))
nodes << (node_piercingstrikes = Node.new('Piercing Strikes',0))
nodes << (node_canopener = Node.new('Can Opener',0))
nodes << (node_piercetheheavens = Node.new('Pierce The Heavens',5))
nodes << (node_resistance = Node.new('Resistance',0))
nodes << (node_elementalendurance = Node.new('Elemental Endurance',0))
nodes << (node_hardy = Node.new('Hardy',3))
nodes << (node_stoic = Node.new('Stoic',5))
nodes << (node_indominable = Node.new('Indominable',8))
nodes << (node_situationalawareness = Node.new('Situational Awareness',5))
nodes << (node_pickpocket = Node.new('Pickpocket',0))
nodes << (node_plant = Node.new('Plant',0))
nodes << (node_sneakattack = Node.new('Sneak Attack',0))
nodes << (node_decoy = Node.new('Decoy',0))
nodes << (node_cripplingstrike = Node.new('Crippling Strike',0))
nodes << (node_weepingblade = Node.new('Weeping Blade',0))
nodes << (node_powerstrike = Node.new('Power Strike',0))
nodes << (node_devestatingstrike = Node.new('Devestating Strike',0))
nodes << (node_apocalypsestrike = Node.new('Apocalypse Strike',0))
nodes << (node_technomancy = Node.new('Technomancy',0))
nodes << (node_supportdrone = Node.new('Support Drone',0))
nodes << (node_medicalsuite = Node.new('Medical Suite',0))
nodes << (node_defribulationcontacts = Node.new('Defribulation Contacts',0))
nodes << (node_assaultdrone = Node.new('Assault Drone',0))
nodes << (node_heavyloadout = Node.new('Heavy Loadout',0))
nodes << (node_twincannons = Node.new('Twin Cannons',0))
nodes << (node_incindiaryloadout = Node.new('Incindiary Loadout',0))
nodes << (node_causticloadout = Node.new('Caustic Loadout',0))
nodes << (node_highvoltageloadout = Node.new('High Voltage Loadout',0))
nodes << (node_geometrycoprocessor = Node.new('Geometry Coprocessor',5))
nodes << (node_projectorarray = Node.new('Projector Array',0))
nodes << (node_remotedeliverysystem = Node.new('Remote Delivery System',8))
nodes << (node_autonomy = Node.new('Autonomy',0))
nodes << (node_capacitors = Node.new('Capacitors',0))
nodes << (node_microfusion = Node.new('Microfusion',0))
nodes << (node_multitranseiver = Node.new('Multitranseiver',5))
nodes << (node_remotedigistruct = Node.new('Remote Digistruct',5))
nodes << (node_digistructwiz = Node.new('Digistruct Wiz',0))
nodes << (node_tacticaldrone = Node.new('Tactical Drone',0))
nodes << (node_overload = Node.new('Overload',0))
nodes << (node_immediatereaction = Node.new('Immediate Reaction',0))
nodes << (node_parry = Node.new('Parry',0))
nodes << (node_sirenity = Node.new('Sirenity',-1))
nodes << (node_phasepooling = Node.new('Phase Pooling',0))
nodes << (node_phasestrike = Node.new('Phase Strike',0))
nodes << (node_phaselock = Node.new('Phase Lock',0))
nodes << (node_phasejaunt = Node.new('Phase Jaunt',0))
nodes << (node_phasebattery = Node.new('Phase Battery',0))
nodes << (node_phaseshield = Node.new('Phase Shield',0))
nodes << (node_phaseshift = Node.new('Phase Shift',0))
nodes << (node_holdphase = Node.new('Hold Phase',8))
nodes << (node_eridiumburn = Node.new('Eridium Burn',0))
nodes << (node_incindiaryphase = Node.new('Incindiary Phase',5))
nodes << (node_causticphase = Node.new('Caustic Phase',5))
nodes << (node_shockingphase = Node.new('Shocking Phase',5))
nodes << (node_cryogenicphase = Node.new('Cryogenic Phase',8))
nodes << (node_phaseburst = Node.new('Phase Burst',8))
nodes << (node_phasebond = Node.new('Phase Bond',0))
nodes << (node_telephase = Node.new('Telephase',5))
nodes << (node_etherialchains = Node.new('Etherial Chains',0))
nodes << (node_phasesyphon = Node.new('Phase Syphon',5))
nodes << (node_sirenegrace = Node.new('Sirene Grace',0))
nodes << (node_angelicgrace = Node.new('Angelic Grace',0))
nodes << (node_gracefulaura = Node.new('Graceful Aura',0))
nodes << (node_overdrivengrace = Node.new('Overdriven Grace',8))
nodes << (node_directedgrace = Node.new('Directed Grace',5))
nodes << (node_phasearmor = Node.new('Phase Armor',0))
nodes << (node_phasereflexes = Node.new('Phase Reflexes',0))
nodes << (node_finalphase = Node.new('Final Phase',12))
nodes << (node_assaultturret = Node.new('Assault Turret',0))
nodes << (node_turretbarrier = Node.new('Turret Barrier',0))
nodes << (node_turretarmor = Node.new('Turret Armor',0))
nodes << (node_extrabarrel = Node.new('Extra Barrel',0))
nodes << (node_supportsystems = Node.new('Support Systems',0))
nodes << (node_improvedoptics = Node.new('Improved Optics',0))
nodes << (node_extendedpowercell = Node.new('Extended Powercell',5))
nodes << (node_explosiveshells = Node.new('Explosive Shells',0))
nodes << (node_turretclamp = Node.new('Turret Clamp',0))
nodes << (node_longbowsystems = Node.new('Longbow Systems',8))
nodes << (node_turrentshield = Node.new('Turrent Shield',5))
nodes << (node_grenadesystem = Node.new('Grenade System',5))
nodes << (node_rocketsystem = Node.new('Rocket System',0))
nodes << (node_devestatingdeploy = Node.new('Devestating Deploy',8))
nodes << (node_lightlyarmored = Node.new('Lightly Armored',0))
nodes << (node_moderatelyarmored = Node.new('Moderately Armored',0))
nodes << (node_heavilyarmored = Node.new('Heavily Armored',0))
nodes << (node_incrediblestrength = Node.new('Incredible Strength',0))
nodes << (node_immovable = Node.new('Immovable',0))
nodes << (node_walkingtank = Node.new('Walking Tank',0))
nodes << (node_digistructplating = Node.new('Digistruct Plating',0))
nodes << (node_shieldlink = Node.new('Shield Link',0))
nodes << (node_shieldbending = Node.new('Shieldbending',0))
nodes << (node_shieldmerge = Node.new('Shield Merge',0))
nodes << (node_shieldoverclocking = Node.new('Shield Overclocking',0))
nodes << (node_shieldoverload = Node.new('Shield Overload',0))
nodes << (node_shieldhardening = Node.new('Shield Hardening',0))
nodes << (node_shieldsyphon = Node.new('Shield Syphon',0))
nodes << (node_shieldnode = Node.new('Shield Node',5))
nodes << (node_shieldtxarray = Node.new('Shield TX Array',0))
nodes << (node_shieldrxarray = Node.new('Shield RX Array',0))
nodes << (node_shieldbattery = Node.new('Shield Battery',0))
nodes << (node_shieldnexus = Node.new('Shield Nexus',8))
nodes << (node_shieldcontrolvirus = Node.new('Shield Control Virus',5))
nodes << (node_shieldcoprocessor = Node.new('Shield Coprocessor',0))
nodes << (node_shieldwatercooling = Node.new('Shield Watercooling',0))
node_finesse.add_child(node_carefulaim)
node_carefulaim.add_child(node_steadyaim)
node_steadyaim.add_child(node_sniper)
node_sniper.add_child(node_cripplingshot)
node_finesse.add_child(node_deadeye)
node_finesse.add_child(node_gunjuggler)
node_deadeye.add_child(node_showdown)
node_gunjuggler.add_child(node_showdown)
node_sprayandpray.add_child(node_itchytriggerfinger)
node_itchytriggerfinger.add_child(node_steadyhands)
node_finesse.add_child(node_calledshot)
node_calledshot.add_child(node_penetratingshot)
node_aid.add_child(node_cauterize)
node_cauterize.add_child(node_defribulatinground)
node_summonminion.add_child(node_summonally)
node_summonally.add_child(node_summonpatron)
node_summonminion.add_child(node_minionstrike)
node_minionstrike.add_child(node_minionbounce)
node_minionbounce.add_child(node_minionchain)
node_minionstrike.add_child(node_minionelement)
node_minionelement.add_child(node_igneousminion)
node_minionelement.add_child(node_chargedminion)
node_minionelement.add_child(node_alkalineminion)
node_minionelement.add_child(node_frostedminion)
node_minionelement.add_child(node_slaggingminion)
node_minionstrike.add_child(node_minionprime)
node_minionstrike.add_child(node_carefulminion)
node_minionstrike.add_child(node_deadlyminion)
node_summonminion.add_child(node_beastmaster)
node_summonminion.add_child(node_menagerie)
node_summonminion.add_child(node_synergisticlink)
node_bulk.add_child(node_toughness)
node_toughness.add_child(node_musclebound)
node_bulk.add_child(node_bastion)
node_bastion.add_child(node_ironchurch)
node_ironchurch.add_child(node_flex)
node_bulk.add_child(node_onehandedwonder)
node_onehandedwonder.add_child(node_gunzerking)
node_toughness.add_child(node_rage)
node_rage.add_child(node_unignorable)
node_rage.add_child(node_unstoppable)
node_rage.add_child(node_unbreakable)
node_rage.add_child(node_hellhathnofury)
node_unbreakable.add_child(node_juggernaut)
node_rage.add_child(node_juggernaut)
node_tackle.add_child(node_bullrush)
node_bullrush.add_child(node_hammerthrow)
node_finesse.add_child(node_dodge)
node_dodge.add_child(node_evasive)
node_evasive.add_child(node_dexterity)
node_dodge.add_child(node_uncannyreflex)
node_rush.add_child(node_sideswipe)
node_sideswipe.add_child(node_murderchain)
node_murderchain.add_child(node_toofasttolive)
node_piercingstrikes.add_child(node_canopener)
node_canopener.add_child(node_piercetheheavens)
node_resistance.add_child(node_elementalendurance)
node_finesse.add_child(node_pickpocket)
node_pickpocket.add_child(node_plant)
node_finesse.add_child(node_sneakattack)
node_finesse.add_child(node_decoy)
node_sneakattack.add_child(node_cripplingstrike)
node_cripplingstrike.add_child(node_weepingblade)
node_powerstrike.add_child(node_devestatingstrike)
node_devestatingstrike.add_child(node_apocalypsestrike)
node_technomancy.add_child(node_supportdrone)
node_supportdrone.add_child(node_medicalsuite)
node_medicalsuite.add_child(node_defribulationcontacts)
node_technomancy.add_child(node_assaultdrone)
node_assaultdrone.add_child(node_heavyloadout)
node_assaultdrone.add_child(node_twincannons)
node_heavyloadout.add_child(node_incindiaryloadout)
node_heavyloadout.add_child(node_causticloadout)
node_heavyloadout.add_child(node_highvoltageloadout)
node_heavyloadout.add_child(node_geometrycoprocessor)
node_geometrycoprocessor.add_child(node_projectorarray)
node_geometrycoprocessor.add_child(node_remotedeliverysystem)
node_assaultdrone.add_child(node_autonomy)
node_technomancy.add_child(node_capacitors)
node_technomancy.add_child(node_microfusion)
node_technomancy.add_child(node_multitranseiver)
node_technomancy.add_child(node_remotedigistruct)
node_remotedigistruction.add_child(node_digistructwiz)
node_digistructai.add_child(node_tacticaldrone)
node_digistructoperation.add_child(node_overload)
node_immediatereaction.add_child(node_parry)
node_sirenity.add_child(node_phasepooling)
node_sirenity.add_child(node_phasestrike)
node_phasestrike.add_child(node_phaselock)
node_sirenity.add_child(node_phasejaunt)
node_sirenity.add_child(node_phaseshield)
node_sirenity.add_child(node_phaseshift)
node_sirenity.add_child(node_holdphase)
node_sirenity.add_child(node_eridiumburn)
node_sirenity.add_child(node_incindiaryphase)
node_sirenity.add_child(node_causticphase)
node_sirenity.add_child(node_shockingphase)
node_sirenity.add_child(node_cryogenicphase)
node_phasestrike.add_child(node_phaseburst)
node_summonminion.add_child(node_phasebond)
node_sirenity.add_child(node_phasebond)
node_phasestrike.add_child(node_phasebond)
node_phasestrike.add_child(node_telephase)
node_telephase.add_child(node_etherialchains)
node_phasestrike.add_child(node_phasesyphon)
node_sirenity.add_child(node_sirenegrace)
node_sirenegrace.add_child(node_angelicgrace)
node_angelicgrace.add_child(node_gracefulaura)
node_angelicgrace.add_child(node_overdrivengrace)
node_angelicgrace.add_child(node_directedgrace)
node_sirenity.add_child(node_phasearmor)
node_sirenity.add_child(node_phasereflexes)
node_sirenity.add_child(node_finalphase)
node_assaultturret.add_child(node_turretbarrier)
node_assaultturret.add_child(node_turretarmor)
node_assaultturrent.add_child(node_extrabarrel)
node_assaultturret.add_child(node_supportsystems)
node_assaultturret.add_child(node_improvedoptics)
node_assaultturret.add_child(node_extendedpowercell)
node_assaultturret.add_child(node_explosiveshells)
node_assaultturret.add_child(node_turretclamp)
node_assaultturret.add_child(node_longbowsystems)
node_assaultturret.add_child(node_turrentshield)
node_assaultturret.add_child(node_grenadesystem)
node_grenadesystem.add_child(node_rocketsystem)
node_rocketsystem.add_child(node_devestatingdeploy)
node_lightlyarmored.add_child(node_moderatelyarmored)
node_moderatelyarmored.add_child(node_heavilyarmored)
node_heavilyarmored.add_child(node_incrediblestrength)
node_heavilyarmored.add_child(node_immovable)
node_heavilyarmored.add_child(node_walkingtank)
node_technomancy.add_child(node_digistructplating)
node_moderatelyarmored.add_child(node_digistructplating)
node_shieldlink.add_child(node_shieldbending)
node_shieldoverclocking.add_child(node_shieldoverload)
node_shieldlink.add_child(node_shieldsyphon)
node_shieldlink.add_child(node_shieldnode)
node_shieldnode.add_child(node_shieldtxarray)
node_shieldnode.add_child(node_shieldrxarray)
node_shieldnode.add_child(node_shieldbattery)
node_shieldtxarray.add_child(node_shieldnexus)
node_shieldrxarray.add_child(node_shieldnexus)
node_shieldnode.add_child(node_shieldcontrolvirus)
node_shieldnode.add_child(node_shieldcoprocessor)
node_shieldnode.add_child(node_shieldwatercooling)


graph = Graph.new
graph.load_data(nodes)
#graph.render
graph.layout